"""empty message

Revision ID: d5bc2a46c97d
Revises: a3092f2542f0
Create Date: 2017-06-04 06:04:40.954341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5bc2a46c97d'
down_revision = 'a3092f2542f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('contact', sa.String(length=32), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('facebook', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('area', sa.String(length=32), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('google_maps', sa.String(length=80), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('hours', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('place_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('place_category_many_to_many',
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('place_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_category_id'], ['place_category.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('place_category_many_to_many')
    op.drop_table('place_category')
    op.drop_table('place')
    # ### end Alembic commands ###
